### ISSUE TITLE
Correct Issue Reporting & Feature Requesting Method

### ISSUE THREAD

**Issue by TheCosmicNebula** [TheCosmosSeries/DimensionalPocketsII#30]
# Correct Issue Reporting & Feature Requesting Method

Please ensure that when you raise a new Issue or request a new Feature, you follow this guide.

***Please also ensure that you have read through all of the closed Issues to ensure you have not submitted a duplicate issue, as any duplicate issues will be closed.***

## Issue:
When reporting an issue, please include the following information:

### **Title**:
[X.XX.X] Brief Description of the Issue

### **Description**:
- Minecraft Version. [Ex: 1.20.1]
- Mod version. [Ex: 9.0.0.0]
- Cosmos-Library Version. [Ex: 10.0.0.0]
- Full crash report. [Which includes a full list of mods being run & the version of forge you are running]
- Whether you where running it on a server, or a client.

This will greatly help when debugging a particular bug or crash.

## **Feature Request:**
When requesting a new feature, please include the following information:
- Include a brief title
- Include a detailed explanation

Thank you greatly in advance,
-- @TheCosmicNebula

**Comment by Kasia1403** [comment]
How to include latest.log and debug.log when all paste sites say "request entity too large or hang when I try to submit a paste ?
